apple = int(input("How many apples you want to buy: "))
amount_of_apples = int(apple * 20)
orange = int(input("How many oranges you want to buy: "))
amount_of_oranges = int (orange * 25)
print(f"The total amount is {amount_of_apples + amount_of_oranges} ")